const iconsPath = "/media/icons/"

export const blockchain = iconsPath + "link.png"
export const logo = iconsPath + "logo.png"
export const walletNotConnected = iconsPath + "wallet-not-connected.png"
export const walletConnectionError = iconsPath + "wallet-connection-error.png"
export const walletConnected = iconsPath + "wallet-connected.png"
export const walletConnecting = iconsPath + "wallet-connecting.png"
export const spotify = iconsPath + "spotify.png"
export const wynk = iconsPath + "wynk.png"
export const loadingAnimatedIcon = iconsPath + "loading.gif"
